### ISSUE TITLE
помоги, пж

### ISSUE THREAD

**Issue by dimasique3six** [alyokhin22/vk-reposter-to-telegram#1]
Привет. Скажи, пожалуйста, правильно ли я понял
TG_ADMIN_CHAT_ID - тут ввожу айдишник бота, которого делаю админом в группе? айдишник в формате 123123123?
TG_CHAT_TO_POST_ID - айдишник группы в таком же формате?

**Comment by alyokhin22** [comment]
> Привет. Скажи, пожалуйста, правильно ли я понял TG_ADMIN_CHAT_ID - тут ввожу айдишник бота, которого делаю админом в группе? айдишник в формате 123123123? TG_CHAT_TO_POST_ID - айдишник группы в таком же формате?

Нет, TG_ADMIN_CHAT_ID - это айди чата, куда бот будет скидывать ошибки и другую ннформацию.
TG_CHAT_TO_POST_ID - непосредственно айди чата или канала, куда нужно скидывать посты

**Comment by dimasique3six** [comment]
![image](https://user-images.githubusercontent.com/59236025/191126193-87271086-7172-4912-9406-11c210f1d775.png)
сорри, я тупенький
как фиксить?)

**Comment by alyokhin22** [comment]
> ![image](https://user-images.githubusercontent.com/59236025/191126193-87271086-7172-4912-9406-11c210f1d775.png) сорри, я тупенький как фиксить?)

Скорее всего, запускаешь старой версией Node.JS. Нужно пробовать на версии не ниже 12

**Comment by dimasique3six** [comment]
> 

![image](https://user-images.githubusercontent.com/59236025/191128236-f0de89a6-557b-4fe0-bec4-85b9fcd5af59.png)
ты был прав, да, но теперь вот))))))))

**Comment by alyokhin22** [comment]
Вообще я не оказываю поддержку по своим скриптам. По крайней мере бесплатную. Если нужна какая-то помощь, можно обратиться ко мне напрямую по моим контактам.

Issue можно открывать, если с самим скриптом что-то не так и вы хотите предложить что-то изменить
